'use client';

import React from 'react';
// import type { Metadata } from 'next';
import StyledJsxRegistry from '../lib/registry';
import { RecoilRoot, RecoilEnv } from 'recoil';
// These styles apply to every route in the application
import './globals.css';
import { Noto_Sans_KR } from 'next/font/google';
import { GlobalStyle } from '@/styles/global-styles';
import { CssBaseline, ThemeProvider } from '@mui/material';
import { RootProvider } from '@/blog/components/common/RootProvider';
import { ToastContainer } from 'react-toastify';
import { rootStore } from '@/store';

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

const notoSansKR = Noto_Sans_KR({
    weight: '100',
    display: 'swap',
    subsets: ['latin'],
});

RecoilEnv.RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED = false;

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={notoSansKR.className}>
            <body>
                <StyledJsxRegistry>
                    <RecoilRoot>
                        <ThemeProvider theme={rootStore.themeStore.main}>
                            <CssBaseline />
                            <GlobalStyle />
                            <RootProvider>{children}</RootProvider>
                        </ThemeProvider>
                        <ToastContainer />
                    </RecoilRoot>
                </StyledJsxRegistry>
            </body>
        </html>
    );
}
